# Generated by Django 5.0.4 on 2024-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_ingredient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='safety',
            field=models.CharField(choices=[('S', 'Safe'), ('N', 'Neutral'), ('R', 'Risky')], default='N', max_length=1),
        ),
    ]
