# Generated by Django 5.0.4 on 2024-05-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_rename_ingredient_item_ingredients_ingredient_safety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
