# Generated by Django 5.0.4 on 2024-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rename_ingredients_item_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
