# Generated by Django 5.0.4 on 2024-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_ingredient_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='safety',
            field=models.CharField(choices=[('S', 'Safe'), ('N', 'Neutral'), ('R', 'Risky')], default='N', max_length=1),
        ),
    ]
